// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstate.Data;

namespace RealEstate.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190723173604_Adding more attributes to property object")]
    partial class Addingmoreattributestopropertyobject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RealEstate.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<bool>("HasAirConditioning");

                    b.Property<bool>("HasBalcony");

                    b.Property<bool>("HasBroadband");

                    b.Property<bool>("HasFloorboards");

                    b.Property<bool>("HasRemoteGarage");

                    b.Property<DateTimeOffset>("LastUpdatedUtc");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfBathrooms");

                    b.Property<int>("NumberOfBedrooms");

                    b.Property<float>("Price");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a beautiful property. Look at its ID of 1",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 22, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(2982), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 1",
                            NumberOfBathrooms = 1,
                            NumberOfBedrooms = 2,
                            Price = 10000f
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is a beautiful property. Look at its ID of 2",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 21, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5639), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 2",
                            NumberOfBathrooms = 2,
                            NumberOfBedrooms = 3,
                            Price = 20000f
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is a beautiful property. Look at its ID of 3",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 20, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5659), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 3",
                            NumberOfBathrooms = 3,
                            NumberOfBedrooms = 4,
                            Price = 30000f
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is a beautiful property. Look at its ID of 4",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 19, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5662), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 4",
                            NumberOfBathrooms = 4,
                            NumberOfBedrooms = 5,
                            Price = 40000f
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is a beautiful property. Look at its ID of 5",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 18, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5664), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 5",
                            NumberOfBathrooms = 5,
                            NumberOfBedrooms = 6,
                            Price = 50000f
                        },
                        new
                        {
                            Id = 6,
                            Description = "This is a beautiful property. Look at its ID of 6",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 17, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5668), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 6",
                            NumberOfBathrooms = 6,
                            NumberOfBedrooms = 7,
                            Price = 60000f
                        },
                        new
                        {
                            Id = 7,
                            Description = "This is a beautiful property. Look at its ID of 7",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 16, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5670), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 7",
                            NumberOfBathrooms = 7,
                            NumberOfBedrooms = 8,
                            Price = 70000f
                        },
                        new
                        {
                            Id = 8,
                            Description = "This is a beautiful property. Look at its ID of 8",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 15, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5672), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 8",
                            NumberOfBathrooms = 8,
                            NumberOfBedrooms = 9,
                            Price = 80000f
                        },
                        new
                        {
                            Id = 9,
                            Description = "This is a beautiful property. Look at its ID of 9",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 14, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5674), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 9",
                            NumberOfBathrooms = 9,
                            NumberOfBedrooms = 10,
                            Price = 90000f
                        },
                        new
                        {
                            Id = 10,
                            Description = "This is a beautiful property. Look at its ID of 10",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 13, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5676), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 10",
                            NumberOfBathrooms = 10,
                            NumberOfBedrooms = 11,
                            Price = 100000f
                        },
                        new
                        {
                            Id = 11,
                            Description = "This is a beautiful property. Look at its ID of 11",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 12, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5678), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 11",
                            NumberOfBathrooms = 11,
                            NumberOfBedrooms = 12,
                            Price = 110000f
                        },
                        new
                        {
                            Id = 12,
                            Description = "This is a beautiful property. Look at its ID of 12",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 11, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5680), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 12",
                            NumberOfBathrooms = 12,
                            NumberOfBedrooms = 13,
                            Price = 120000f
                        },
                        new
                        {
                            Id = 13,
                            Description = "This is a beautiful property. Look at its ID of 13",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = true,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 10, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5780), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 13",
                            NumberOfBathrooms = 13,
                            NumberOfBedrooms = 14,
                            Price = 130000f
                        },
                        new
                        {
                            Id = 14,
                            Description = "This is a beautiful property. Look at its ID of 14",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 9, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5783), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 14",
                            NumberOfBathrooms = 14,
                            NumberOfBedrooms = 15,
                            Price = 140000f
                        },
                        new
                        {
                            Id = 15,
                            Description = "This is a beautiful property. Look at its ID of 15",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 8, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5785), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 15",
                            NumberOfBathrooms = 15,
                            NumberOfBedrooms = 16,
                            Price = 150000f
                        },
                        new
                        {
                            Id = 16,
                            Description = "This is a beautiful property. Look at its ID of 16",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 7, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5787), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 16",
                            NumberOfBathrooms = 16,
                            NumberOfBedrooms = 17,
                            Price = 160000f
                        },
                        new
                        {
                            Id = 17,
                            Description = "This is a beautiful property. Look at its ID of 17",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 6, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5789), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 17",
                            NumberOfBathrooms = 17,
                            NumberOfBedrooms = 18,
                            Price = 170000f
                        },
                        new
                        {
                            Id = 18,
                            Description = "This is a beautiful property. Look at its ID of 18",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 5, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5792), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 18",
                            NumberOfBathrooms = 18,
                            NumberOfBedrooms = 19,
                            Price = 180000f
                        },
                        new
                        {
                            Id = 19,
                            Description = "This is a beautiful property. Look at its ID of 19",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 4, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5793), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 19",
                            NumberOfBathrooms = 19,
                            NumberOfBedrooms = 20,
                            Price = 190000f
                        },
                        new
                        {
                            Id = 20,
                            Description = "This is a beautiful property. Look at its ID of 20",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 3, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5795), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 20",
                            NumberOfBathrooms = 20,
                            NumberOfBedrooms = 21,
                            Price = 200000f
                        },
                        new
                        {
                            Id = 21,
                            Description = "This is a beautiful property. Look at its ID of 21",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 2, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5797), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 21",
                            NumberOfBathrooms = 21,
                            NumberOfBedrooms = 22,
                            Price = 210000f
                        },
                        new
                        {
                            Id = 22,
                            Description = "This is a beautiful property. Look at its ID of 22",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 7, 1, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5798), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 22",
                            NumberOfBathrooms = 22,
                            NumberOfBedrooms = 23,
                            Price = 220000f
                        },
                        new
                        {
                            Id = 23,
                            Description = "This is a beautiful property. Look at its ID of 23",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 30, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5800), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 23",
                            NumberOfBathrooms = 23,
                            NumberOfBedrooms = 24,
                            Price = 230000f
                        },
                        new
                        {
                            Id = 24,
                            Description = "This is a beautiful property. Look at its ID of 24",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 29, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5802), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 24",
                            NumberOfBathrooms = 24,
                            NumberOfBedrooms = 25,
                            Price = 240000f
                        },
                        new
                        {
                            Id = 25,
                            Description = "This is a beautiful property. Look at its ID of 25",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 28, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5804), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 25",
                            NumberOfBathrooms = 25,
                            NumberOfBedrooms = 26,
                            Price = 250000f
                        },
                        new
                        {
                            Id = 26,
                            Description = "This is a beautiful property. Look at its ID of 26",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = true,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 27, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5806), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 26",
                            NumberOfBathrooms = 26,
                            NumberOfBedrooms = 27,
                            Price = 260000f
                        },
                        new
                        {
                            Id = 27,
                            Description = "This is a beautiful property. Look at its ID of 27",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 26, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5808), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 27",
                            NumberOfBathrooms = 27,
                            NumberOfBedrooms = 28,
                            Price = 270000f
                        },
                        new
                        {
                            Id = 28,
                            Description = "This is a beautiful property. Look at its ID of 28",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 25, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5809), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 28",
                            NumberOfBathrooms = 28,
                            NumberOfBedrooms = 29,
                            Price = 280000f
                        },
                        new
                        {
                            Id = 29,
                            Description = "This is a beautiful property. Look at its ID of 29",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 24, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5811), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 29",
                            NumberOfBathrooms = 29,
                            NumberOfBedrooms = 30,
                            Price = 290000f
                        },
                        new
                        {
                            Id = 30,
                            Description = "This is a beautiful property. Look at its ID of 30",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 23, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5813), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 30",
                            NumberOfBathrooms = 30,
                            NumberOfBedrooms = 31,
                            Price = 300000f
                        },
                        new
                        {
                            Id = 31,
                            Description = "This is a beautiful property. Look at its ID of 31",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 22, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5815), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 31",
                            NumberOfBathrooms = 31,
                            NumberOfBedrooms = 32,
                            Price = 310000f
                        },
                        new
                        {
                            Id = 32,
                            Description = "This is a beautiful property. Look at its ID of 32",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 21, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5816), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 32",
                            NumberOfBathrooms = 32,
                            NumberOfBedrooms = 33,
                            Price = 320000f
                        },
                        new
                        {
                            Id = 33,
                            Description = "This is a beautiful property. Look at its ID of 33",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 20, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5818), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 33",
                            NumberOfBathrooms = 33,
                            NumberOfBedrooms = 34,
                            Price = 330000f
                        },
                        new
                        {
                            Id = 34,
                            Description = "This is a beautiful property. Look at its ID of 34",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 19, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5856), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 34",
                            NumberOfBathrooms = 34,
                            NumberOfBedrooms = 35,
                            Price = 340000f
                        },
                        new
                        {
                            Id = 35,
                            Description = "This is a beautiful property. Look at its ID of 35",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 18, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5858), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 35",
                            NumberOfBathrooms = 35,
                            NumberOfBedrooms = 36,
                            Price = 350000f
                        },
                        new
                        {
                            Id = 36,
                            Description = "This is a beautiful property. Look at its ID of 36",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 17, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5860), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 36",
                            NumberOfBathrooms = 36,
                            NumberOfBedrooms = 37,
                            Price = 360000f
                        },
                        new
                        {
                            Id = 37,
                            Description = "This is a beautiful property. Look at its ID of 37",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 16, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5862), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 37",
                            NumberOfBathrooms = 37,
                            NumberOfBedrooms = 38,
                            Price = 370000f
                        },
                        new
                        {
                            Id = 38,
                            Description = "This is a beautiful property. Look at its ID of 38",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 15, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5863), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 38",
                            NumberOfBathrooms = 38,
                            NumberOfBedrooms = 39,
                            Price = 380000f
                        },
                        new
                        {
                            Id = 39,
                            Description = "This is a beautiful property. Look at its ID of 39",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = true,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 14, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5865), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 39",
                            NumberOfBathrooms = 39,
                            NumberOfBedrooms = 40,
                            Price = 390000f
                        },
                        new
                        {
                            Id = 40,
                            Description = "This is a beautiful property. Look at its ID of 40",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 13, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5867), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 40",
                            NumberOfBathrooms = 40,
                            NumberOfBedrooms = 41,
                            Price = 400000f
                        },
                        new
                        {
                            Id = 41,
                            Description = "This is a beautiful property. Look at its ID of 41",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 12, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5868), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 41",
                            NumberOfBathrooms = 41,
                            NumberOfBedrooms = 42,
                            Price = 410000f
                        },
                        new
                        {
                            Id = 42,
                            Description = "This is a beautiful property. Look at its ID of 42",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 11, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5870), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 42",
                            NumberOfBathrooms = 42,
                            NumberOfBedrooms = 43,
                            Price = 420000f
                        },
                        new
                        {
                            Id = 43,
                            Description = "This is a beautiful property. Look at its ID of 43",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 10, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5872), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 43",
                            NumberOfBathrooms = 43,
                            NumberOfBedrooms = 44,
                            Price = 430000f
                        },
                        new
                        {
                            Id = 44,
                            Description = "This is a beautiful property. Look at its ID of 44",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 9, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5874), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 44",
                            NumberOfBathrooms = 44,
                            NumberOfBedrooms = 45,
                            Price = 440000f
                        },
                        new
                        {
                            Id = 45,
                            Description = "This is a beautiful property. Look at its ID of 45",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 8, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5875), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 45",
                            NumberOfBathrooms = 45,
                            NumberOfBedrooms = 46,
                            Price = 450000f
                        },
                        new
                        {
                            Id = 46,
                            Description = "This is a beautiful property. Look at its ID of 46",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 7, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5877), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 46",
                            NumberOfBathrooms = 46,
                            NumberOfBedrooms = 47,
                            Price = 460000f
                        },
                        new
                        {
                            Id = 47,
                            Description = "This is a beautiful property. Look at its ID of 47",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 6, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5879), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 47",
                            NumberOfBathrooms = 47,
                            NumberOfBedrooms = 48,
                            Price = 470000f
                        },
                        new
                        {
                            Id = 48,
                            Description = "This is a beautiful property. Look at its ID of 48",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 5, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5881), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 48",
                            NumberOfBathrooms = 48,
                            NumberOfBedrooms = 49,
                            Price = 480000f
                        },
                        new
                        {
                            Id = 49,
                            Description = "This is a beautiful property. Look at its ID of 49",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 4, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5882), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 49",
                            NumberOfBathrooms = 49,
                            NumberOfBedrooms = 50,
                            Price = 490000f
                        },
                        new
                        {
                            Id = 50,
                            Description = "This is a beautiful property. Look at its ID of 50",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 3, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5884), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 50",
                            NumberOfBathrooms = 50,
                            NumberOfBedrooms = 51,
                            Price = 500000f
                        },
                        new
                        {
                            Id = 51,
                            Description = "This is a beautiful property. Look at its ID of 51",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 2, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5886), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 51",
                            NumberOfBathrooms = 51,
                            NumberOfBedrooms = 52,
                            Price = 510000f
                        },
                        new
                        {
                            Id = 52,
                            Description = "This is a beautiful property. Look at its ID of 52",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = true,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 6, 1, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5888), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 52",
                            NumberOfBathrooms = 52,
                            NumberOfBedrooms = 53,
                            Price = 520000f
                        },
                        new
                        {
                            Id = 53,
                            Description = "This is a beautiful property. Look at its ID of 53",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 31, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5889), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 53",
                            NumberOfBathrooms = 53,
                            NumberOfBedrooms = 54,
                            Price = 530000f
                        },
                        new
                        {
                            Id = 54,
                            Description = "This is a beautiful property. Look at its ID of 54",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 30, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5891), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 54",
                            NumberOfBathrooms = 54,
                            NumberOfBedrooms = 55,
                            Price = 540000f
                        },
                        new
                        {
                            Id = 55,
                            Description = "This is a beautiful property. Look at its ID of 55",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 29, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5893), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 55",
                            NumberOfBathrooms = 55,
                            NumberOfBedrooms = 56,
                            Price = 550000f
                        },
                        new
                        {
                            Id = 56,
                            Description = "This is a beautiful property. Look at its ID of 56",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 28, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5894), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 56",
                            NumberOfBathrooms = 56,
                            NumberOfBedrooms = 57,
                            Price = 560000f
                        },
                        new
                        {
                            Id = 57,
                            Description = "This is a beautiful property. Look at its ID of 57",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 27, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5927), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 57",
                            NumberOfBathrooms = 57,
                            NumberOfBedrooms = 58,
                            Price = 570000f
                        },
                        new
                        {
                            Id = 58,
                            Description = "This is a beautiful property. Look at its ID of 58",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 26, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5929), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 58",
                            NumberOfBathrooms = 58,
                            NumberOfBedrooms = 59,
                            Price = 580000f
                        },
                        new
                        {
                            Id = 59,
                            Description = "This is a beautiful property. Look at its ID of 59",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 25, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5930), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 59",
                            NumberOfBathrooms = 59,
                            NumberOfBedrooms = 60,
                            Price = 590000f
                        },
                        new
                        {
                            Id = 60,
                            Description = "This is a beautiful property. Look at its ID of 60",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 24, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5932), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 60",
                            NumberOfBathrooms = 60,
                            NumberOfBedrooms = 61,
                            Price = 600000f
                        },
                        new
                        {
                            Id = 61,
                            Description = "This is a beautiful property. Look at its ID of 61",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 23, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5934), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 61",
                            NumberOfBathrooms = 61,
                            NumberOfBedrooms = 62,
                            Price = 610000f
                        },
                        new
                        {
                            Id = 62,
                            Description = "This is a beautiful property. Look at its ID of 62",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 22, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5936), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 62",
                            NumberOfBathrooms = 62,
                            NumberOfBedrooms = 63,
                            Price = 620000f
                        },
                        new
                        {
                            Id = 63,
                            Description = "This is a beautiful property. Look at its ID of 63",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 21, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5937), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 63",
                            NumberOfBathrooms = 63,
                            NumberOfBedrooms = 64,
                            Price = 630000f
                        },
                        new
                        {
                            Id = 64,
                            Description = "This is a beautiful property. Look at its ID of 64",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 20, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5939), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 64",
                            NumberOfBathrooms = 64,
                            NumberOfBedrooms = 65,
                            Price = 640000f
                        },
                        new
                        {
                            Id = 65,
                            Description = "This is a beautiful property. Look at its ID of 65",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = true,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 19, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5941), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 65",
                            NumberOfBathrooms = 65,
                            NumberOfBedrooms = 66,
                            Price = 650000f
                        },
                        new
                        {
                            Id = 66,
                            Description = "This is a beautiful property. Look at its ID of 66",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 18, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5943), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 66",
                            NumberOfBathrooms = 66,
                            NumberOfBedrooms = 67,
                            Price = 660000f
                        },
                        new
                        {
                            Id = 67,
                            Description = "This is a beautiful property. Look at its ID of 67",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 17, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5945), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 67",
                            NumberOfBathrooms = 67,
                            NumberOfBedrooms = 68,
                            Price = 670000f
                        },
                        new
                        {
                            Id = 68,
                            Description = "This is a beautiful property. Look at its ID of 68",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 16, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5947), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 68",
                            NumberOfBathrooms = 68,
                            NumberOfBedrooms = 69,
                            Price = 680000f
                        },
                        new
                        {
                            Id = 69,
                            Description = "This is a beautiful property. Look at its ID of 69",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 15, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5949), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 69",
                            NumberOfBathrooms = 69,
                            NumberOfBedrooms = 70,
                            Price = 690000f
                        },
                        new
                        {
                            Id = 70,
                            Description = "This is a beautiful property. Look at its ID of 70",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 14, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5950), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 70",
                            NumberOfBathrooms = 70,
                            NumberOfBedrooms = 71,
                            Price = 700000f
                        },
                        new
                        {
                            Id = 71,
                            Description = "This is a beautiful property. Look at its ID of 71",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 13, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5952), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 71",
                            NumberOfBathrooms = 71,
                            NumberOfBedrooms = 72,
                            Price = 710000f
                        },
                        new
                        {
                            Id = 72,
                            Description = "This is a beautiful property. Look at its ID of 72",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 12, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5954), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 72",
                            NumberOfBathrooms = 72,
                            NumberOfBedrooms = 73,
                            Price = 720000f
                        },
                        new
                        {
                            Id = 73,
                            Description = "This is a beautiful property. Look at its ID of 73",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 11, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5956), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 73",
                            NumberOfBathrooms = 73,
                            NumberOfBedrooms = 74,
                            Price = 730000f
                        },
                        new
                        {
                            Id = 74,
                            Description = "This is a beautiful property. Look at its ID of 74",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 10, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5957), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 74",
                            NumberOfBathrooms = 74,
                            NumberOfBedrooms = 75,
                            Price = 740000f
                        },
                        new
                        {
                            Id = 75,
                            Description = "This is a beautiful property. Look at its ID of 75",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 9, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5959), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 75",
                            NumberOfBathrooms = 75,
                            NumberOfBedrooms = 76,
                            Price = 750000f
                        },
                        new
                        {
                            Id = 76,
                            Description = "This is a beautiful property. Look at its ID of 76",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 8, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5988), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 76",
                            NumberOfBathrooms = 76,
                            NumberOfBedrooms = 77,
                            Price = 760000f
                        },
                        new
                        {
                            Id = 77,
                            Description = "This is a beautiful property. Look at its ID of 77",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 7, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5990), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 77",
                            NumberOfBathrooms = 77,
                            NumberOfBedrooms = 78,
                            Price = 770000f
                        },
                        new
                        {
                            Id = 78,
                            Description = "This is a beautiful property. Look at its ID of 78",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = true,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 6, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5992), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 78",
                            NumberOfBathrooms = 78,
                            NumberOfBedrooms = 79,
                            Price = 780000f
                        },
                        new
                        {
                            Id = 79,
                            Description = "This is a beautiful property. Look at its ID of 79",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 5, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5993), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 79",
                            NumberOfBathrooms = 79,
                            NumberOfBedrooms = 80,
                            Price = 790000f
                        },
                        new
                        {
                            Id = 80,
                            Description = "This is a beautiful property. Look at its ID of 80",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 4, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5995), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 80",
                            NumberOfBathrooms = 80,
                            NumberOfBedrooms = 81,
                            Price = 800000f
                        },
                        new
                        {
                            Id = 81,
                            Description = "This is a beautiful property. Look at its ID of 81",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 3, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5997), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 81",
                            NumberOfBathrooms = 81,
                            NumberOfBedrooms = 82,
                            Price = 810000f
                        },
                        new
                        {
                            Id = 82,
                            Description = "This is a beautiful property. Look at its ID of 82",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 2, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(5999), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 82",
                            NumberOfBathrooms = 82,
                            NumberOfBedrooms = 83,
                            Price = 820000f
                        },
                        new
                        {
                            Id = 83,
                            Description = "This is a beautiful property. Look at its ID of 83",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 5, 1, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6001), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 83",
                            NumberOfBathrooms = 83,
                            NumberOfBedrooms = 84,
                            Price = 830000f
                        },
                        new
                        {
                            Id = 84,
                            Description = "This is a beautiful property. Look at its ID of 84",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 30, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6002), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 84",
                            NumberOfBathrooms = 84,
                            NumberOfBedrooms = 85,
                            Price = 840000f
                        },
                        new
                        {
                            Id = 85,
                            Description = "This is a beautiful property. Look at its ID of 85",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 29, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6004), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 85",
                            NumberOfBathrooms = 85,
                            NumberOfBedrooms = 86,
                            Price = 850000f
                        },
                        new
                        {
                            Id = 86,
                            Description = "This is a beautiful property. Look at its ID of 86",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 28, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6006), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 86",
                            NumberOfBathrooms = 86,
                            NumberOfBedrooms = 87,
                            Price = 860000f
                        },
                        new
                        {
                            Id = 87,
                            Description = "This is a beautiful property. Look at its ID of 87",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 27, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6007), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 87",
                            NumberOfBathrooms = 87,
                            NumberOfBedrooms = 88,
                            Price = 870000f
                        },
                        new
                        {
                            Id = 88,
                            Description = "This is a beautiful property. Look at its ID of 88",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 26, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6009), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 88",
                            NumberOfBathrooms = 88,
                            NumberOfBedrooms = 89,
                            Price = 880000f
                        },
                        new
                        {
                            Id = 89,
                            Description = "This is a beautiful property. Look at its ID of 89",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 25, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6011), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 89",
                            NumberOfBathrooms = 89,
                            NumberOfBedrooms = 90,
                            Price = 890000f
                        },
                        new
                        {
                            Id = 90,
                            Description = "This is a beautiful property. Look at its ID of 90",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 24, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6012), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 90",
                            NumberOfBathrooms = 90,
                            NumberOfBedrooms = 91,
                            Price = 900000f
                        },
                        new
                        {
                            Id = 91,
                            Description = "This is a beautiful property. Look at its ID of 91",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = true,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 23, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6014), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 91",
                            NumberOfBathrooms = 91,
                            NumberOfBedrooms = 92,
                            Price = 910000f
                        },
                        new
                        {
                            Id = 92,
                            Description = "This is a beautiful property. Look at its ID of 92",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 22, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6016), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 92",
                            NumberOfBathrooms = 92,
                            NumberOfBedrooms = 93,
                            Price = 920000f
                        },
                        new
                        {
                            Id = 93,
                            Description = "This is a beautiful property. Look at its ID of 93",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 21, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6017), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 93",
                            NumberOfBathrooms = 93,
                            NumberOfBedrooms = 94,
                            Price = 930000f
                        },
                        new
                        {
                            Id = 94,
                            Description = "This is a beautiful property. Look at its ID of 94",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 20, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6019), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 94",
                            NumberOfBathrooms = 94,
                            NumberOfBedrooms = 95,
                            Price = 940000f
                        },
                        new
                        {
                            Id = 95,
                            Description = "This is a beautiful property. Look at its ID of 95",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = true,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 19, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6021), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 95",
                            NumberOfBathrooms = 95,
                            NumberOfBedrooms = 96,
                            Price = 950000f
                        },
                        new
                        {
                            Id = 96,
                            Description = "This is a beautiful property. Look at its ID of 96",
                            HasAirConditioning = true,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 18, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6023), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 96",
                            NumberOfBathrooms = 96,
                            NumberOfBedrooms = 97,
                            Price = 960000f
                        },
                        new
                        {
                            Id = 97,
                            Description = "This is a beautiful property. Look at its ID of 97",
                            HasAirConditioning = false,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 17, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6024), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 97",
                            NumberOfBathrooms = 97,
                            NumberOfBedrooms = 98,
                            Price = 970000f
                        },
                        new
                        {
                            Id = 98,
                            Description = "This is a beautiful property. Look at its ID of 98",
                            HasAirConditioning = true,
                            HasBalcony = false,
                            HasBroadband = false,
                            HasFloorboards = true,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 16, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6026), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 98",
                            NumberOfBathrooms = 98,
                            NumberOfBedrooms = 99,
                            Price = 980000f
                        },
                        new
                        {
                            Id = 99,
                            Description = "This is a beautiful property. Look at its ID of 99",
                            HasAirConditioning = false,
                            HasBalcony = true,
                            HasBroadband = false,
                            HasFloorboards = false,
                            HasRemoteGarage = false,
                            LastUpdatedUtc = new DateTimeOffset(new DateTime(2019, 4, 15, 17, 36, 3, 849, DateTimeKind.Unspecified).AddTicks(6054), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Property 99",
                            NumberOfBathrooms = 99,
                            NumberOfBedrooms = 100,
                            Price = 990000f
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
