using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace RealEstate.Migrations
{
    public partial class ResetDB : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Properties",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    Description = table.Column<string>(nullable: true),
                    Price = table.Column<float>(nullable: false),
                    NumberOfBathrooms = table.Column<int>(nullable: false),
                    NumberOfBedrooms = table.Column<int>(nullable: false),
                    LastUpdatedUtc = table.Column<DateTimeOffset>(nullable: false),
                    HasAirConditioning = table.Column<bool>(nullable: false),
                    HasBroadband = table.Column<bool>(nullable: false),
                    HasBalcony = table.Column<bool>(nullable: false),
                    HasRemoteGarage = table.Column<bool>(nullable: false),
                    HasFloorboards = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Properties", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "PropertyAssets",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    PropertyId = table.Column<int>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    ImageUrl = table.Column<string>(nullable: true),
                    ThumbnailUrl = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PropertyAssets", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PropertyAssets_Properties_PropertyId",
                        column: x => x.PropertyId,
                        principalTable: "Properties",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Properties",
                columns: new[] { "Id", "Description", "HasAirConditioning", "HasBalcony", "HasBroadband", "HasFloorboards", "HasRemoteGarage", "LastUpdatedUtc", "Name", "NumberOfBathrooms", "NumberOfBedrooms", "Price" },
                values: new object[,]
                {
                    { 1, "This is a beautiful property. Look at its ID of 1", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 23, 13, 36, 47, 809, DateTimeKind.Unspecified).AddTicks(6616), new TimeSpan(0, 0, 0, 0, 0)), "Property 1", 1, 2, 10000f },
                    { 73, "This is a beautiful property. Look at its ID of 73", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 12, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7886), new TimeSpan(0, 0, 0, 0, 0)), "Property 73", 73, 74, 730000f },
                    { 72, "This is a beautiful property. Look at its ID of 72", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 13, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7868), new TimeSpan(0, 0, 0, 0, 0)), "Property 72", 72, 73, 720000f },
                    { 71, "This is a beautiful property. Look at its ID of 71", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 14, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7796), new TimeSpan(0, 0, 0, 0, 0)), "Property 71", 71, 72, 710000f },
                    { 70, "This is a beautiful property. Look at its ID of 70", true, false, true, true, false, new DateTimeOffset(new DateTime(2019, 5, 15, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7780), new TimeSpan(0, 0, 0, 0, 0)), "Property 70", 70, 71, 700000f },
                    { 69, "This is a beautiful property. Look at its ID of 69", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 16, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7764), new TimeSpan(0, 0, 0, 0, 0)), "Property 69", 69, 70, 690000f },
                    { 68, "This is a beautiful property. Look at its ID of 68", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 17, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7748), new TimeSpan(0, 0, 0, 0, 0)), "Property 68", 68, 69, 680000f },
                    { 67, "This is a beautiful property. Look at its ID of 67", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 18, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7732), new TimeSpan(0, 0, 0, 0, 0)), "Property 67", 67, 68, 670000f },
                    { 66, "This is a beautiful property. Look at its ID of 66", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 19, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7715), new TimeSpan(0, 0, 0, 0, 0)), "Property 66", 66, 67, 660000f },
                    { 65, "This is a beautiful property. Look at its ID of 65", false, false, true, false, true, new DateTimeOffset(new DateTime(2019, 5, 20, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7635), new TimeSpan(0, 0, 0, 0, 0)), "Property 65", 65, 66, 650000f },
                    { 64, "This is a beautiful property. Look at its ID of 64", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 21, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7619), new TimeSpan(0, 0, 0, 0, 0)), "Property 64", 64, 65, 640000f },
                    { 63, "This is a beautiful property. Look at its ID of 63", false, true, false, true, false, new DateTimeOffset(new DateTime(2019, 5, 22, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7603), new TimeSpan(0, 0, 0, 0, 0)), "Property 63", 63, 64, 630000f },
                    { 62, "This is a beautiful property. Look at its ID of 62", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 23, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7587), new TimeSpan(0, 0, 0, 0, 0)), "Property 62", 62, 63, 620000f },
                    { 61, "This is a beautiful property. Look at its ID of 61", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 24, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7496), new TimeSpan(0, 0, 0, 0, 0)), "Property 61", 61, 62, 610000f },
                    { 60, "This is a beautiful property. Look at its ID of 60", true, true, true, false, false, new DateTimeOffset(new DateTime(2019, 5, 25, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7480), new TimeSpan(0, 0, 0, 0, 0)), "Property 60", 60, 61, 600000f },
                    { 59, "This is a beautiful property. Look at its ID of 59", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 26, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7463), new TimeSpan(0, 0, 0, 0, 0)), "Property 59", 59, 60, 590000f },
                    { 58, "This is a beautiful property. Look at its ID of 58", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 27, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7447), new TimeSpan(0, 0, 0, 0, 0)), "Property 58", 58, 59, 580000f },
                    { 57, "This is a beautiful property. Look at its ID of 57", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 28, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7431), new TimeSpan(0, 0, 0, 0, 0)), "Property 57", 57, 58, 570000f },
                    { 56, "This is a beautiful property. Look at its ID of 56", true, false, false, true, false, new DateTimeOffset(new DateTime(2019, 5, 29, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7415), new TimeSpan(0, 0, 0, 0, 0)), "Property 56", 56, 57, 560000f },
                    { 55, "This is a beautiful property. Look at its ID of 55", false, false, true, false, false, new DateTimeOffset(new DateTime(2019, 5, 30, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7342), new TimeSpan(0, 0, 0, 0, 0)), "Property 55", 55, 56, 550000f },
                    { 54, "This is a beautiful property. Look at its ID of 54", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 31, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7326), new TimeSpan(0, 0, 0, 0, 0)), "Property 54", 54, 55, 540000f },
                    { 53, "This is a beautiful property. Look at its ID of 53", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 1, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7310), new TimeSpan(0, 0, 0, 0, 0)), "Property 53", 53, 54, 530000f },
                    { 74, "This is a beautiful property. Look at its ID of 74", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 11, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7902), new TimeSpan(0, 0, 0, 0, 0)), "Property 74", 74, 75, 740000f },
                    { 52, "This is a beautiful property. Look at its ID of 52", true, false, false, false, true, new DateTimeOffset(new DateTime(2019, 6, 2, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7294), new TimeSpan(0, 0, 0, 0, 0)), "Property 52", 52, 53, 520000f },
                    { 75, "This is a beautiful property. Look at its ID of 75", false, true, true, false, false, new DateTimeOffset(new DateTime(2019, 5, 10, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7918), new TimeSpan(0, 0, 0, 0, 0)), "Property 75", 75, 76, 750000f },
                    { 77, "This is a beautiful property. Look at its ID of 77", false, false, false, true, false, new DateTimeOffset(new DateTime(2019, 5, 8, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7950), new TimeSpan(0, 0, 0, 0, 0)), "Property 77", 77, 78, 770000f },
                    { 98, "This is a beautiful property. Look at its ID of 98", true, false, false, true, false, new DateTimeOffset(new DateTime(2019, 4, 17, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8511), new TimeSpan(0, 0, 0, 0, 0)), "Property 98", 98, 99, 980000f },
                    { 97, "This is a beautiful property. Look at its ID of 97", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 18, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8438), new TimeSpan(0, 0, 0, 0, 0)), "Property 97", 97, 98, 970000f },
                    { 96, "This is a beautiful property. Look at its ID of 96", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 19, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8422), new TimeSpan(0, 0, 0, 0, 0)), "Property 96", 96, 97, 960000f },
                    { 95, "This is a beautiful property. Look at its ID of 95", false, false, true, false, false, new DateTimeOffset(new DateTime(2019, 4, 20, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8405), new TimeSpan(0, 0, 0, 0, 0)), "Property 95", 95, 96, 950000f },
                    { 94, "This is a beautiful property. Look at its ID of 94", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 21, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8389), new TimeSpan(0, 0, 0, 0, 0)), "Property 94", 94, 95, 940000f },
                    { 93, "This is a beautiful property. Look at its ID of 93", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 22, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8373), new TimeSpan(0, 0, 0, 0, 0)), "Property 93", 93, 94, 930000f },
                    { 92, "This is a beautiful property. Look at its ID of 92", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 23, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8357), new TimeSpan(0, 0, 0, 0, 0)), "Property 92", 92, 93, 920000f },
                    { 91, "This is a beautiful property. Look at its ID of 91", false, false, false, true, true, new DateTimeOffset(new DateTime(2019, 4, 24, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8339), new TimeSpan(0, 0, 0, 0, 0)), "Property 91", 91, 92, 910000f },
                    { 90, "This is a beautiful property. Look at its ID of 90", true, true, true, false, false, new DateTimeOffset(new DateTime(2019, 4, 25, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8269), new TimeSpan(0, 0, 0, 0, 0)), "Property 90", 90, 91, 900000f },
                    { 89, "This is a beautiful property. Look at its ID of 89", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 26, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8253), new TimeSpan(0, 0, 0, 0, 0)), "Property 89", 89, 90, 890000f },
                    { 88, "This is a beautiful property. Look at its ID of 88", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 27, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8237), new TimeSpan(0, 0, 0, 0, 0)), "Property 88", 88, 89, 880000f },
                    { 87, "This is a beautiful property. Look at its ID of 87", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 28, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8221), new TimeSpan(0, 0, 0, 0, 0)), "Property 87", 87, 88, 870000f },
                    { 86, "This is a beautiful property. Look at its ID of 86", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 29, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8205), new TimeSpan(0, 0, 0, 0, 0)), "Property 86", 86, 87, 860000f },
                    { 85, "This is a beautiful property. Look at its ID of 85", false, false, true, false, false, new DateTimeOffset(new DateTime(2019, 4, 30, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8189), new TimeSpan(0, 0, 0, 0, 0)), "Property 85", 85, 86, 850000f },
                    { 84, "This is a beautiful property. Look at its ID of 84", true, true, false, true, false, new DateTimeOffset(new DateTime(2019, 5, 1, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8117), new TimeSpan(0, 0, 0, 0, 0)), "Property 84", 84, 85, 840000f },
                    { 83, "This is a beautiful property. Look at its ID of 83", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 2, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8101), new TimeSpan(0, 0, 0, 0, 0)), "Property 83", 83, 84, 830000f },
                    { 82, "This is a beautiful property. Look at its ID of 82", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 3, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8085), new TimeSpan(0, 0, 0, 0, 0)), "Property 82", 82, 83, 820000f },
                    { 81, "This is a beautiful property. Look at its ID of 81", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 4, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8068), new TimeSpan(0, 0, 0, 0, 0)), "Property 81", 81, 82, 810000f },
                    { 80, "This is a beautiful property. Look at its ID of 80", true, false, true, false, false, new DateTimeOffset(new DateTime(2019, 5, 5, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8052), new TimeSpan(0, 0, 0, 0, 0)), "Property 80", 80, 81, 800000f },
                    { 79, "This is a beautiful property. Look at its ID of 79", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 6, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8036), new TimeSpan(0, 0, 0, 0, 0)), "Property 79", 79, 80, 790000f },
                    { 78, "This is a beautiful property. Look at its ID of 78", true, true, false, false, true, new DateTimeOffset(new DateTime(2019, 5, 7, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7966), new TimeSpan(0, 0, 0, 0, 0)), "Property 78", 78, 79, 780000f },
                    { 76, "This is a beautiful property. Look at its ID of 76", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 5, 9, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7934), new TimeSpan(0, 0, 0, 0, 0)), "Property 76", 76, 77, 760000f },
                    { 51, "This is a beautiful property. Look at its ID of 51", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 3, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7278), new TimeSpan(0, 0, 0, 0, 0)), "Property 51", 51, 52, 510000f },
                    { 50, "This is a beautiful property. Look at its ID of 50", true, false, true, false, false, new DateTimeOffset(new DateTime(2019, 6, 4, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7262), new TimeSpan(0, 0, 0, 0, 0)), "Property 50", 50, 51, 500000f },
                    { 49, "This is a beautiful property. Look at its ID of 49", false, false, false, true, false, new DateTimeOffset(new DateTime(2019, 6, 5, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7245), new TimeSpan(0, 0, 0, 0, 0)), "Property 49", 49, 50, 490000f },
                    { 22, "This is a beautiful property. Look at its ID of 22", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 2, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6459), new TimeSpan(0, 0, 0, 0, 0)), "Property 22", 22, 23, 220000f },
                    { 21, "This is a beautiful property. Look at its ID of 21", false, true, false, true, false, new DateTimeOffset(new DateTime(2019, 7, 3, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6443), new TimeSpan(0, 0, 0, 0, 0)), "Property 21", 21, 22, 210000f },
                    { 20, "This is a beautiful property. Look at its ID of 20", true, false, true, false, false, new DateTimeOffset(new DateTime(2019, 7, 4, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6427), new TimeSpan(0, 0, 0, 0, 0)), "Property 20", 20, 21, 200000f },
                    { 19, "This is a beautiful property. Look at its ID of 19", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 5, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6410), new TimeSpan(0, 0, 0, 0, 0)), "Property 19", 19, 20, 190000f },
                    { 18, "This is a beautiful property. Look at its ID of 18", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 6, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6335), new TimeSpan(0, 0, 0, 0, 0)), "Property 18", 18, 19, 180000f },
                    { 17, "This is a beautiful property. Look at its ID of 17", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 7, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6317), new TimeSpan(0, 0, 0, 0, 0)), "Property 17", 17, 18, 170000f },
                    { 16, "This is a beautiful property. Look at its ID of 16", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 8, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6301), new TimeSpan(0, 0, 0, 0, 0)), "Property 16", 16, 17, 160000f },
                    { 15, "This is a beautiful property. Look at its ID of 15", false, true, true, false, false, new DateTimeOffset(new DateTime(2019, 7, 9, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6284), new TimeSpan(0, 0, 0, 0, 0)), "Property 15", 15, 16, 150000f },
                    { 14, "This is a beautiful property. Look at its ID of 14", true, false, false, true, false, new DateTimeOffset(new DateTime(2019, 7, 10, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6268), new TimeSpan(0, 0, 0, 0, 0)), "Property 14", 14, 15, 140000f },
                    { 13, "This is a beautiful property. Look at its ID of 13", false, false, false, false, true, new DateTimeOffset(new DateTime(2019, 7, 11, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6250), new TimeSpan(0, 0, 0, 0, 0)), "Property 13", 13, 14, 130000f },
                    { 12, "This is a beautiful property. Look at its ID of 12", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 12, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6144), new TimeSpan(0, 0, 0, 0, 0)), "Property 12", 12, 13, 120000f },
                    { 11, "This is a beautiful property. Look at its ID of 11", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 13, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6127), new TimeSpan(0, 0, 0, 0, 0)), "Property 11", 11, 12, 110000f },
                    { 10, "This is a beautiful property. Look at its ID of 10", true, false, true, false, false, new DateTimeOffset(new DateTime(2019, 7, 14, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6111), new TimeSpan(0, 0, 0, 0, 0)), "Property 10", 10, 11, 100000f },
                    { 9, "This is a beautiful property. Look at its ID of 9", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 15, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6093), new TimeSpan(0, 0, 0, 0, 0)), "Property 9", 9, 10, 90000f },
                    { 8, "This is a beautiful property. Look at its ID of 8", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 16, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6077), new TimeSpan(0, 0, 0, 0, 0)), "Property 8", 8, 9, 80000f },
                    { 7, "This is a beautiful property. Look at its ID of 7", false, false, false, true, false, new DateTimeOffset(new DateTime(2019, 7, 17, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6059), new TimeSpan(0, 0, 0, 0, 0)), "Property 7", 7, 8, 70000f },
                    { 6, "This is a beautiful property. Look at its ID of 6", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 18, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(5955), new TimeSpan(0, 0, 0, 0, 0)), "Property 6", 6, 7, 60000f },
                    { 5, "This is a beautiful property. Look at its ID of 5", false, false, true, false, false, new DateTimeOffset(new DateTime(2019, 7, 19, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(5937), new TimeSpan(0, 0, 0, 0, 0)), "Property 5", 5, 6, 50000f },
                    { 4, "This is a beautiful property. Look at its ID of 4", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 20, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(5920), new TimeSpan(0, 0, 0, 0, 0)), "Property 4", 4, 5, 40000f },
                    { 3, "This is a beautiful property. Look at its ID of 3", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 21, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(5899), new TimeSpan(0, 0, 0, 0, 0)), "Property 3", 3, 4, 30000f },
                    { 2, "This is a beautiful property. Look at its ID of 2", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 22, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(5858), new TimeSpan(0, 0, 0, 0, 0)), "Property 2", 2, 3, 20000f },
                    { 23, "This is a beautiful property. Look at its ID of 23", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 7, 1, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6475), new TimeSpan(0, 0, 0, 0, 0)), "Property 23", 23, 24, 230000f },
                    { 24, "This is a beautiful property. Look at its ID of 24", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 30, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6491), new TimeSpan(0, 0, 0, 0, 0)), "Property 24", 24, 25, 240000f },
                    { 25, "This is a beautiful property. Look at its ID of 25", false, false, true, false, false, new DateTimeOffset(new DateTime(2019, 6, 29, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6567), new TimeSpan(0, 0, 0, 0, 0)), "Property 25", 25, 26, 250000f },
                    { 26, "This is a beautiful property. Look at its ID of 26", true, false, false, false, true, new DateTimeOffset(new DateTime(2019, 6, 28, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6583), new TimeSpan(0, 0, 0, 0, 0)), "Property 26", 26, 27, 260000f },
                    { 48, "This is a beautiful property. Look at its ID of 48", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 6, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7116), new TimeSpan(0, 0, 0, 0, 0)), "Property 48", 48, 49, 480000f },
                    { 47, "This is a beautiful property. Look at its ID of 47", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 7, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7100), new TimeSpan(0, 0, 0, 0, 0)), "Property 47", 47, 48, 470000f },
                    { 46, "This is a beautiful property. Look at its ID of 46", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 8, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7084), new TimeSpan(0, 0, 0, 0, 0)), "Property 46", 46, 47, 460000f },
                    { 45, "This is a beautiful property. Look at its ID of 45", false, true, true, false, false, new DateTimeOffset(new DateTime(2019, 6, 9, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7067), new TimeSpan(0, 0, 0, 0, 0)), "Property 45", 45, 46, 450000f },
                    { 44, "This is a beautiful property. Look at its ID of 44", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 10, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7050), new TimeSpan(0, 0, 0, 0, 0)), "Property 44", 44, 45, 440000f },
                    { 43, "This is a beautiful property. Look at its ID of 43", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 11, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(7034), new TimeSpan(0, 0, 0, 0, 0)), "Property 43", 43, 44, 430000f },
                    { 42, "This is a beautiful property. Look at its ID of 42", true, true, false, true, false, new DateTimeOffset(new DateTime(2019, 6, 12, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6962), new TimeSpan(0, 0, 0, 0, 0)), "Property 42", 42, 43, 420000f },
                    { 41, "This is a beautiful property. Look at its ID of 41", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 13, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6947), new TimeSpan(0, 0, 0, 0, 0)), "Property 41", 41, 42, 410000f },
                    { 40, "This is a beautiful property. Look at its ID of 40", true, false, true, false, false, new DateTimeOffset(new DateTime(2019, 6, 14, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6931), new TimeSpan(0, 0, 0, 0, 0)), "Property 40", 40, 41, 400000f },
                    { 39, "This is a beautiful property. Look at its ID of 39", false, true, false, false, true, new DateTimeOffset(new DateTime(2019, 6, 15, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6915), new TimeSpan(0, 0, 0, 0, 0)), "Property 39", 39, 40, 390000f },
                    { 99, "This is a beautiful property. Look at its ID of 99", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 4, 16, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8527), new TimeSpan(0, 0, 0, 0, 0)), "Property 99", 99, 100, 990000f },
                    { 38, "This is a beautiful property. Look at its ID of 38", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 16, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6898), new TimeSpan(0, 0, 0, 0, 0)), "Property 38", 38, 39, 380000f },
                    { 36, "This is a beautiful property. Look at its ID of 36", true, true, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 18, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6809), new TimeSpan(0, 0, 0, 0, 0)), "Property 36", 36, 37, 360000f },
                    { 35, "This is a beautiful property. Look at its ID of 35", false, false, true, true, false, new DateTimeOffset(new DateTime(2019, 6, 19, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6793), new TimeSpan(0, 0, 0, 0, 0)), "Property 35", 35, 36, 350000f },
                    { 34, "This is a beautiful property. Look at its ID of 34", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 20, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6777), new TimeSpan(0, 0, 0, 0, 0)), "Property 34", 34, 35, 340000f },
                    { 33, "This is a beautiful property. Look at its ID of 33", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 21, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6759), new TimeSpan(0, 0, 0, 0, 0)), "Property 33", 33, 34, 330000f },
                    { 32, "This is a beautiful property. Look at its ID of 32", true, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 22, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6743), new TimeSpan(0, 0, 0, 0, 0)), "Property 32", 32, 33, 320000f },
                    { 31, "This is a beautiful property. Look at its ID of 31", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 23, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6663), new TimeSpan(0, 0, 0, 0, 0)), "Property 31", 31, 32, 310000f },
                    { 30, "This is a beautiful property. Look at its ID of 30", true, true, true, false, false, new DateTimeOffset(new DateTime(2019, 6, 24, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6647), new TimeSpan(0, 0, 0, 0, 0)), "Property 30", 30, 31, 300000f },
                    { 29, "This is a beautiful property. Look at its ID of 29", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 25, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6631), new TimeSpan(0, 0, 0, 0, 0)), "Property 29", 29, 30, 290000f },
                    { 28, "This is a beautiful property. Look at its ID of 28", true, false, false, true, false, new DateTimeOffset(new DateTime(2019, 6, 26, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6615), new TimeSpan(0, 0, 0, 0, 0)), "Property 28", 28, 29, 280000f },
                    { 27, "This is a beautiful property. Look at its ID of 27", false, true, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 27, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6599), new TimeSpan(0, 0, 0, 0, 0)), "Property 27", 27, 28, 270000f },
                    { 37, "This is a beautiful property. Look at its ID of 37", false, false, false, false, false, new DateTimeOffset(new DateTime(2019, 6, 17, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(6882), new TimeSpan(0, 0, 0, 0, 0)), "Property 37", 37, 38, 370000f },
                    { 100, "This is a beautiful property. Look at its ID of 100", true, false, true, false, false, new DateTimeOffset(new DateTime(2019, 4, 15, 13, 36, 47, 810, DateTimeKind.Unspecified).AddTicks(8544), new TimeSpan(0, 0, 0, 0, 0)), "Property 100", 100, 101, 1000000f }
                });

            migrationBuilder.InsertData(
                table: "PropertyAssets",
                columns: new[] { "Id", "Description", "ImageUrl", "PropertyId", "ThumbnailUrl" },
                values: new object[,]
                {
                    { 1, "Image 1 for property 1", "/assets/demopropertyimages/property-1.jpg", 1, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 128, "Image 2 for property 64", "/assets/demopropertyimages/property-0.jpg", 64, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 129, "Image 1 for property 65", "/assets/demopropertyimages/property-1.jpg", 65, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 130, "Image 2 for property 65", "/assets/demopropertyimages/property-1.jpg", 65, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 131, "Image 1 for property 66", "/assets/demopropertyimages/property-2.jpg", 66, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 132, "Image 2 for property 66", "/assets/demopropertyimages/property-2.jpg", 66, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 133, "Image 1 for property 67", "/assets/demopropertyimages/property-3.jpg", 67, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 134, "Image 2 for property 67", "/assets/demopropertyimages/property-3.jpg", 67, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 135, "Image 1 for property 68", "/assets/demopropertyimages/property-4.jpg", 68, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 136, "Image 2 for property 68", "/assets/demopropertyimages/property-4.jpg", 68, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 137, "Image 1 for property 69", "/assets/demopropertyimages/property-5.jpg", 69, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 138, "Image 2 for property 69", "/assets/demopropertyimages/property-5.jpg", 69, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 139, "Image 1 for property 70", "/assets/demopropertyimages/property-6.jpg", 70, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 140, "Image 2 for property 70", "/assets/demopropertyimages/property-6.jpg", 70, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 141, "Image 1 for property 71", "/assets/demopropertyimages/property-7.jpg", 71, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 142, "Image 2 for property 71", "/assets/demopropertyimages/property-7.jpg", 71, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 143, "Image 1 for property 72", "/assets/demopropertyimages/property-0.jpg", 72, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 144, "Image 2 for property 72", "/assets/demopropertyimages/property-0.jpg", 72, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 145, "Image 1 for property 73", "/assets/demopropertyimages/property-1.jpg", 73, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 146, "Image 2 for property 73", "/assets/demopropertyimages/property-1.jpg", 73, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 147, "Image 1 for property 74", "/assets/demopropertyimages/property-2.jpg", 74, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 148, "Image 2 for property 74", "/assets/demopropertyimages/property-2.jpg", 74, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 127, "Image 1 for property 64", "/assets/demopropertyimages/property-0.jpg", 64, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 149, "Image 1 for property 75", "/assets/demopropertyimages/property-3.jpg", 75, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 126, "Image 2 for property 63", "/assets/demopropertyimages/property-7.jpg", 63, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 124, "Image 2 for property 62", "/assets/demopropertyimages/property-6.jpg", 62, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 103, "Image 1 for property 52", "/assets/demopropertyimages/property-4.jpg", 52, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 104, "Image 2 for property 52", "/assets/demopropertyimages/property-4.jpg", 52, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 105, "Image 1 for property 53", "/assets/demopropertyimages/property-5.jpg", 53, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 106, "Image 2 for property 53", "/assets/demopropertyimages/property-5.jpg", 53, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 107, "Image 1 for property 54", "/assets/demopropertyimages/property-6.jpg", 54, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 108, "Image 2 for property 54", "/assets/demopropertyimages/property-6.jpg", 54, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 109, "Image 1 for property 55", "/assets/demopropertyimages/property-7.jpg", 55, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 110, "Image 2 for property 55", "/assets/demopropertyimages/property-7.jpg", 55, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 111, "Image 1 for property 56", "/assets/demopropertyimages/property-0.jpg", 56, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 112, "Image 2 for property 56", "/assets/demopropertyimages/property-0.jpg", 56, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 113, "Image 1 for property 57", "/assets/demopropertyimages/property-1.jpg", 57, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 114, "Image 2 for property 57", "/assets/demopropertyimages/property-1.jpg", 57, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 115, "Image 1 for property 58", "/assets/demopropertyimages/property-2.jpg", 58, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 116, "Image 2 for property 58", "/assets/demopropertyimages/property-2.jpg", 58, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 117, "Image 1 for property 59", "/assets/demopropertyimages/property-3.jpg", 59, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 118, "Image 2 for property 59", "/assets/demopropertyimages/property-3.jpg", 59, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 119, "Image 1 for property 60", "/assets/demopropertyimages/property-4.jpg", 60, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 120, "Image 2 for property 60", "/assets/demopropertyimages/property-4.jpg", 60, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 121, "Image 1 for property 61", "/assets/demopropertyimages/property-5.jpg", 61, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 122, "Image 2 for property 61", "/assets/demopropertyimages/property-5.jpg", 61, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 123, "Image 1 for property 62", "/assets/demopropertyimages/property-6.jpg", 62, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 125, "Image 1 for property 63", "/assets/demopropertyimages/property-7.jpg", 63, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 102, "Image 2 for property 51", "/assets/demopropertyimages/property-3.jpg", 51, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 150, "Image 2 for property 75", "/assets/demopropertyimages/property-3.jpg", 75, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 152, "Image 2 for property 76", "/assets/demopropertyimages/property-4.jpg", 76, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 178, "Image 2 for property 89", "/assets/demopropertyimages/property-1.jpg", 89, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 179, "Image 1 for property 90", "/assets/demopropertyimages/property-2.jpg", 90, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 180, "Image 2 for property 90", "/assets/demopropertyimages/property-2.jpg", 90, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 181, "Image 1 for property 91", "/assets/demopropertyimages/property-3.jpg", 91, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 182, "Image 2 for property 91", "/assets/demopropertyimages/property-3.jpg", 91, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 183, "Image 1 for property 92", "/assets/demopropertyimages/property-4.jpg", 92, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 184, "Image 2 for property 92", "/assets/demopropertyimages/property-4.jpg", 92, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 185, "Image 1 for property 93", "/assets/demopropertyimages/property-5.jpg", 93, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 186, "Image 2 for property 93", "/assets/demopropertyimages/property-5.jpg", 93, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 187, "Image 1 for property 94", "/assets/demopropertyimages/property-6.jpg", 94, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 188, "Image 2 for property 94", "/assets/demopropertyimages/property-6.jpg", 94, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 189, "Image 1 for property 95", "/assets/demopropertyimages/property-7.jpg", 95, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 190, "Image 2 for property 95", "/assets/demopropertyimages/property-7.jpg", 95, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 191, "Image 1 for property 96", "/assets/demopropertyimages/property-0.jpg", 96, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 192, "Image 2 for property 96", "/assets/demopropertyimages/property-0.jpg", 96, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 193, "Image 1 for property 97", "/assets/demopropertyimages/property-1.jpg", 97, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 194, "Image 2 for property 97", "/assets/demopropertyimages/property-1.jpg", 97, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 195, "Image 1 for property 98", "/assets/demopropertyimages/property-2.jpg", 98, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 196, "Image 2 for property 98", "/assets/demopropertyimages/property-2.jpg", 98, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 197, "Image 1 for property 99", "/assets/demopropertyimages/property-3.jpg", 99, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 198, "Image 2 for property 99", "/assets/demopropertyimages/property-3.jpg", 99, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 177, "Image 1 for property 89", "/assets/demopropertyimages/property-1.jpg", 89, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 151, "Image 1 for property 76", "/assets/demopropertyimages/property-4.jpg", 76, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 176, "Image 2 for property 88", "/assets/demopropertyimages/property-0.jpg", 88, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 174, "Image 2 for property 87", "/assets/demopropertyimages/property-7.jpg", 87, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 153, "Image 1 for property 77", "/assets/demopropertyimages/property-5.jpg", 77, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 154, "Image 2 for property 77", "/assets/demopropertyimages/property-5.jpg", 77, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 155, "Image 1 for property 78", "/assets/demopropertyimages/property-6.jpg", 78, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 156, "Image 2 for property 78", "/assets/demopropertyimages/property-6.jpg", 78, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 157, "Image 1 for property 79", "/assets/demopropertyimages/property-7.jpg", 79, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 158, "Image 2 for property 79", "/assets/demopropertyimages/property-7.jpg", 79, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 159, "Image 1 for property 80", "/assets/demopropertyimages/property-0.jpg", 80, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 160, "Image 2 for property 80", "/assets/demopropertyimages/property-0.jpg", 80, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 161, "Image 1 for property 81", "/assets/demopropertyimages/property-1.jpg", 81, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 162, "Image 2 for property 81", "/assets/demopropertyimages/property-1.jpg", 81, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 163, "Image 1 for property 82", "/assets/demopropertyimages/property-2.jpg", 82, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 164, "Image 2 for property 82", "/assets/demopropertyimages/property-2.jpg", 82, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 165, "Image 1 for property 83", "/assets/demopropertyimages/property-3.jpg", 83, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 166, "Image 2 for property 83", "/assets/demopropertyimages/property-3.jpg", 83, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 167, "Image 1 for property 84", "/assets/demopropertyimages/property-4.jpg", 84, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 168, "Image 2 for property 84", "/assets/demopropertyimages/property-4.jpg", 84, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 169, "Image 1 for property 85", "/assets/demopropertyimages/property-5.jpg", 85, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 170, "Image 2 for property 85", "/assets/demopropertyimages/property-5.jpg", 85, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 171, "Image 1 for property 86", "/assets/demopropertyimages/property-6.jpg", 86, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 172, "Image 2 for property 86", "/assets/demopropertyimages/property-6.jpg", 86, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 173, "Image 1 for property 87", "/assets/demopropertyimages/property-7.jpg", 87, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 175, "Image 1 for property 88", "/assets/demopropertyimages/property-0.jpg", 88, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 101, "Image 1 for property 51", "/assets/demopropertyimages/property-3.jpg", 51, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 100, "Image 2 for property 50", "/assets/demopropertyimages/property-2.jpg", 50, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 99, "Image 1 for property 50", "/assets/demopropertyimages/property-2.jpg", 50, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 27, "Image 1 for property 14", "/assets/demopropertyimages/property-6.jpg", 14, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 28, "Image 2 for property 14", "/assets/demopropertyimages/property-6.jpg", 14, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 29, "Image 1 for property 15", "/assets/demopropertyimages/property-7.jpg", 15, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 30, "Image 2 for property 15", "/assets/demopropertyimages/property-7.jpg", 15, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 31, "Image 1 for property 16", "/assets/demopropertyimages/property-0.jpg", 16, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 32, "Image 2 for property 16", "/assets/demopropertyimages/property-0.jpg", 16, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 33, "Image 1 for property 17", "/assets/demopropertyimages/property-1.jpg", 17, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 34, "Image 2 for property 17", "/assets/demopropertyimages/property-1.jpg", 17, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 35, "Image 1 for property 18", "/assets/demopropertyimages/property-2.jpg", 18, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 36, "Image 2 for property 18", "/assets/demopropertyimages/property-2.jpg", 18, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 37, "Image 1 for property 19", "/assets/demopropertyimages/property-3.jpg", 19, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 38, "Image 2 for property 19", "/assets/demopropertyimages/property-3.jpg", 19, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 39, "Image 1 for property 20", "/assets/demopropertyimages/property-4.jpg", 20, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 40, "Image 2 for property 20", "/assets/demopropertyimages/property-4.jpg", 20, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 41, "Image 1 for property 21", "/assets/demopropertyimages/property-5.jpg", 21, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 42, "Image 2 for property 21", "/assets/demopropertyimages/property-5.jpg", 21, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 43, "Image 1 for property 22", "/assets/demopropertyimages/property-6.jpg", 22, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 44, "Image 2 for property 22", "/assets/demopropertyimages/property-6.jpg", 22, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 45, "Image 1 for property 23", "/assets/demopropertyimages/property-7.jpg", 23, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 46, "Image 2 for property 23", "/assets/demopropertyimages/property-7.jpg", 23, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 47, "Image 1 for property 24", "/assets/demopropertyimages/property-0.jpg", 24, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 26, "Image 2 for property 13", "/assets/demopropertyimages/property-5.jpg", 13, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 48, "Image 2 for property 24", "/assets/demopropertyimages/property-0.jpg", 24, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 25, "Image 1 for property 13", "/assets/demopropertyimages/property-5.jpg", 13, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 23, "Image 1 for property 12", "/assets/demopropertyimages/property-4.jpg", 12, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 2, "Image 2 for property 1", "/assets/demopropertyimages/property-1.jpg", 1, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 3, "Image 1 for property 2", "/assets/demopropertyimages/property-2.jpg", 2, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 4, "Image 2 for property 2", "/assets/demopropertyimages/property-2.jpg", 2, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 5, "Image 1 for property 3", "/assets/demopropertyimages/property-3.jpg", 3, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 6, "Image 2 for property 3", "/assets/demopropertyimages/property-3.jpg", 3, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 7, "Image 1 for property 4", "/assets/demopropertyimages/property-4.jpg", 4, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 8, "Image 2 for property 4", "/assets/demopropertyimages/property-4.jpg", 4, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 9, "Image 1 for property 5", "/assets/demopropertyimages/property-5.jpg", 5, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 10, "Image 2 for property 5", "/assets/demopropertyimages/property-5.jpg", 5, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 11, "Image 1 for property 6", "/assets/demopropertyimages/property-6.jpg", 6, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 12, "Image 2 for property 6", "/assets/demopropertyimages/property-6.jpg", 6, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 13, "Image 1 for property 7", "/assets/demopropertyimages/property-7.jpg", 7, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 14, "Image 2 for property 7", "/assets/demopropertyimages/property-7.jpg", 7, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 15, "Image 1 for property 8", "/assets/demopropertyimages/property-0.jpg", 8, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 16, "Image 2 for property 8", "/assets/demopropertyimages/property-0.jpg", 8, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 17, "Image 1 for property 9", "/assets/demopropertyimages/property-1.jpg", 9, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 18, "Image 2 for property 9", "/assets/demopropertyimages/property-1.jpg", 9, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 19, "Image 1 for property 10", "/assets/demopropertyimages/property-2.jpg", 10, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 20, "Image 2 for property 10", "/assets/demopropertyimages/property-2.jpg", 10, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 21, "Image 1 for property 11", "/assets/demopropertyimages/property-3.jpg", 11, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 22, "Image 2 for property 11", "/assets/demopropertyimages/property-3.jpg", 11, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 24, "Image 2 for property 12", "/assets/demopropertyimages/property-4.jpg", 12, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 49, "Image 1 for property 25", "/assets/demopropertyimages/property-1.jpg", 25, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 50, "Image 2 for property 25", "/assets/demopropertyimages/property-1.jpg", 25, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 51, "Image 1 for property 26", "/assets/demopropertyimages/property-2.jpg", 26, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 78, "Image 2 for property 39", "/assets/demopropertyimages/property-7.jpg", 39, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 79, "Image 1 for property 40", "/assets/demopropertyimages/property-0.jpg", 40, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 80, "Image 2 for property 40", "/assets/demopropertyimages/property-0.jpg", 40, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 81, "Image 1 for property 41", "/assets/demopropertyimages/property-1.jpg", 41, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 82, "Image 2 for property 41", "/assets/demopropertyimages/property-1.jpg", 41, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 83, "Image 1 for property 42", "/assets/demopropertyimages/property-2.jpg", 42, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 84, "Image 2 for property 42", "/assets/demopropertyimages/property-2.jpg", 42, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 85, "Image 1 for property 43", "/assets/demopropertyimages/property-3.jpg", 43, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 86, "Image 2 for property 43", "/assets/demopropertyimages/property-3.jpg", 43, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 87, "Image 1 for property 44", "/assets/demopropertyimages/property-4.jpg", 44, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 88, "Image 2 for property 44", "/assets/demopropertyimages/property-4.jpg", 44, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 89, "Image 1 for property 45", "/assets/demopropertyimages/property-5.jpg", 45, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 90, "Image 2 for property 45", "/assets/demopropertyimages/property-5.jpg", 45, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 91, "Image 1 for property 46", "/assets/demopropertyimages/property-6.jpg", 46, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 92, "Image 2 for property 46", "/assets/demopropertyimages/property-6.jpg", 46, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 93, "Image 1 for property 47", "/assets/demopropertyimages/property-7.jpg", 47, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 94, "Image 2 for property 47", "/assets/demopropertyimages/property-7.jpg", 47, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 95, "Image 1 for property 48", "/assets/demopropertyimages/property-0.jpg", 48, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 96, "Image 2 for property 48", "/assets/demopropertyimages/property-0.jpg", 48, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 97, "Image 1 for property 49", "/assets/demopropertyimages/property-1.jpg", 49, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 98, "Image 2 for property 49", "/assets/demopropertyimages/property-1.jpg", 49, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 77, "Image 1 for property 39", "/assets/demopropertyimages/property-7.jpg", 39, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 76, "Image 2 for property 38", "/assets/demopropertyimages/property-6.jpg", 38, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 75, "Image 1 for property 38", "/assets/demopropertyimages/property-6.jpg", 38, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 74, "Image 2 for property 37", "/assets/demopropertyimages/property-5.jpg", 37, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 52, "Image 2 for property 26", "/assets/demopropertyimages/property-2.jpg", 26, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 53, "Image 1 for property 27", "/assets/demopropertyimages/property-3.jpg", 27, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 54, "Image 2 for property 27", "/assets/demopropertyimages/property-3.jpg", 27, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 55, "Image 1 for property 28", "/assets/demopropertyimages/property-4.jpg", 28, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 56, "Image 2 for property 28", "/assets/demopropertyimages/property-4.jpg", 28, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 57, "Image 1 for property 29", "/assets/demopropertyimages/property-5.jpg", 29, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 58, "Image 2 for property 29", "/assets/demopropertyimages/property-5.jpg", 29, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 59, "Image 1 for property 30", "/assets/demopropertyimages/property-6.jpg", 30, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 60, "Image 2 for property 30", "/assets/demopropertyimages/property-6.jpg", 30, "/assets/demopropertythumbnails/thumb-property-6.jpg" },
                    { 61, "Image 1 for property 31", "/assets/demopropertyimages/property-7.jpg", 31, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 199, "Image 1 for property 100", "/assets/demopropertyimages/property-4.jpg", 100, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 62, "Image 2 for property 31", "/assets/demopropertyimages/property-7.jpg", 31, "/assets/demopropertythumbnails/thumb-property-7.jpg" },
                    { 64, "Image 2 for property 32", "/assets/demopropertyimages/property-0.jpg", 32, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 65, "Image 1 for property 33", "/assets/demopropertyimages/property-1.jpg", 33, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 66, "Image 2 for property 33", "/assets/demopropertyimages/property-1.jpg", 33, "/assets/demopropertythumbnails/thumb-property-1.jpg" },
                    { 67, "Image 1 for property 34", "/assets/demopropertyimages/property-2.jpg", 34, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 68, "Image 2 for property 34", "/assets/demopropertyimages/property-2.jpg", 34, "/assets/demopropertythumbnails/thumb-property-2.jpg" },
                    { 69, "Image 1 for property 35", "/assets/demopropertyimages/property-3.jpg", 35, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 70, "Image 2 for property 35", "/assets/demopropertyimages/property-3.jpg", 35, "/assets/demopropertythumbnails/thumb-property-3.jpg" },
                    { 71, "Image 1 for property 36", "/assets/demopropertyimages/property-4.jpg", 36, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 72, "Image 2 for property 36", "/assets/demopropertyimages/property-4.jpg", 36, "/assets/demopropertythumbnails/thumb-property-4.jpg" },
                    { 73, "Image 1 for property 37", "/assets/demopropertyimages/property-5.jpg", 37, "/assets/demopropertythumbnails/thumb-property-5.jpg" },
                    { 63, "Image 1 for property 32", "/assets/demopropertyimages/property-0.jpg", 32, "/assets/demopropertythumbnails/thumb-property-0.jpg" },
                    { 200, "Image 2 for property 100", "/assets/demopropertyimages/property-4.jpg", 100, "/assets/demopropertythumbnails/thumb-property-4.jpg" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_PropertyAssets_PropertyId",
                table: "PropertyAssets",
                column: "PropertyId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PropertyAssets");

            migrationBuilder.DropTable(
                name: "Properties");
        }
    }
}
